# Generated by Django 5.0.6 on 2024-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefas",
            name="data_final",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tarefas",
            name="data_terminada",
            field=models.DateField(null=True),
        ),
    ]
